let day=document.querySelector(".day")
let c = document.querySelector(".c")
let del = document.querySelector(".delete")
let plus=document.querySelector(".plus")
let divide = document.querySelector(".divide")
let multiply=document.querySelector(".multiply")
let minus=document.querySelector(".minus")
let dot = document.querySelector(".dot")
let equal=document.querySelector(".equal")
let one=document.querySelector(".one")
let two=document.querySelector(".two")
let three=document.querySelector(".three")
let four=document.querySelector(".four")
let five=document.querySelector(".five")
let six=document.querySelector(".six")
let seven=document.querySelector(".seven")
let eight=document.querySelector(".eight")
let nine=document.querySelector(".nine")
let zero=document.querySelector(".zero")
let container=document.querySelector(".container")
let playground=document.querySelector(".playground")
day.onclick=function(){
    day.className="night"
    container.style.backgroundColor="black"
    day.style.cssText=" margin-top: 10px;background-color:white; width: 20px;height: 20px;border-radius: 50%;margin-left: 445px;cursor:pointer"
    c.style.backgroundColor="#2d191e"
    c.style.color="#bd3740"
    del.style.backgroundColor="#2d191e"
    del.style.color="#bd3740"
    plus.style.color="#aa00a4"
    plus.style.backgroundColor="#2e1f39"
    multiply.style.color="#aa00a4"
    multiply.style.backgroundColor="#2e1f39"
    divide.style.color="#aa00a4"
    divide.style.backgroundColor="#2e1f39"
    minus.style.color="#aa00a4"
    minus.style.backgroundColor="#2e1f39"
    dot.style.color="#aa00a4"
    dot.style.backgroundColor="#2e1f39"
    equal.style.backgroundColor="#223323"
    equal.style.color="#ffffff"
    one.style.backgroundColor="#1b2f38"
    one.style.color="#f8fafb"
    two.style.backgroundColor="#1b2f38"
    two.style.color="#f8fafb"
    three.style.backgroundColor="#1b2f38"
    three.style.color="#f8fafb"
    four.style.backgroundColor="#1b2f38"
    four.style.color="#f8fafb"
    five.style.backgroundColor="#1b2f38"
    five.style.color="#f8fafb"
    six.style.backgroundColor="#1b2f38"
    six.style.color="#f8fafb"
    seven.style.backgroundColor="#1b2f38"
    seven.style.color="#f8fafb"
    eight.style.backgroundColor="#1b2f38"
    eight.style.color="#f8fafb"
    nine.style.backgroundColor="#1b2f38"
    nine.style.color="#f8fafb"
    zero.style.backgroundColor="#1b2f38"
    zero.style.color="#f8fafb"
    let night=document.querySelector(".night")
}

